### ISSUE TITLE
set content from database?

### ISSUE THREAD

**Issue by leo4all** [eusonlito/laravel-Meta#11]
Would be nice to have content set from database identified by slug or route

**Comment by eusonlito** [comment]
I don't understand your request, can you provide an example? :)

**Comment by leo4all** [comment]
Like set in midleware or in another place the content for Metatags, using DB as page source.

$page = Page::where('route /  slug', $request->route->getName() )->get();
Meta::title($page->title);

**Comment by eusonlito** [comment]
Yes, you can do it without problem from controller. Check README examples.
