### ISSUE TITLE
You're missing a critical step

### ISSUE THREAD

**Issue by theianjohnson** [eusonlito/laravel-Meta#14]
Looks like you might be missing a piece in your readme when dealing with setting default values in Controller.php - 

Your HomeController.php needs a
```
public function __construct()
    {
        parent::__construct();
    }
```
Otherwise your defaults don't get called

**Comment by eusonlito** [comment]
Nope, on my example `HomeController` extends `Controller` and `HomeController` don't need to referer to parent `__construct` if it doesn't have a own `__construct`. `HomeController` inherits the parent constructor.

**Comment by theianjohnson** [comment]
Ahh I see, I think the Laravel installed HomeController.php came with  a __construct() function, but wasn't calling its parent - so in my case I needed to either remove the __construction() from HomeController.php _or_ add the parent call. Cheers!
