### ISSUE TITLE
No way to remove images?

### ISSUE THREAD

**Issue by theianjohnson** [eusonlito/laravel-Meta#15]
Here's my use case - 

LinkedIn only seems to grab the first og:image
I set a default "catch all" image in Controller.php
I set more specific images in controllers that extend Controller.php
I output images with `{!! Meta::tag('image') !!}`

Is there any way to -

Unset a previously set image? Or override an image? Or reverse the order of the images?

**Comment by eusonlito** [comment]
Avoid to set a default image into constructor.

As example show:

```html
    <head>
        ...

        {{-- Print custom section images and a default image if not set --}}
        {!! Meta::tag('image', asset('images/default-logo.png')) !!}
    </head>
```

**Comment by theianjohnson** [comment]
That does work, but being able to set a default image then override it seems like a pretty common use case

No worries if it's not something you're looking to add, I'll take a look around and see if any other Laravel libraries implement it like this, cheers!

**Comment by eusonlito** [comment]
Please, upgrade to last release `v3.1.1` :)
