### ISSUE TITLE
Package Auto-Discovery for Laravel 5.5

### ISSUE THREAD

**Issue by kkomelin** [eusonlito/laravel-Meta#17]
[Package Auto-Discovery](https://laravel.com/docs/5.5/packages#package-discovery) significantly simplifies installation of Laravel packages. It would be great to have this feature implemented in laravel-Meta.

If you don't mind, I will provide a PR in a few minutes.

**Comment by eusonlito** [comment]
Merged. Thanks a lot!

**Comment by kkomelin** [comment]
@eusonlito Thanks for reviewing and merging my PR and for your project ;)

**Comment by kkomelin** [comment]
@eusonlito Could you please make a release for the project?

**Comment by eusonlito** [comment]
Done!

**Comment by kkomelin** [comment]
@eusonlito Great. Thank you very much!
