### ISSUE TITLE
Option to set image_base for absolute image URLs

### ISSUE THREAD

**Issue by bellwood** [eusonlito/laravel-Meta#25]
I am using laravel mix for my images which generates a relative path to the image via mix().

I'm finding myself repetitively prepending `env('APP_URL')` in my `meta::set('image','...')` so my images are absolutely pathed.

Could we have a option in config.php for `'image_base' => env('APP_URL')` to permit this functionality?

Thank you =)

**Comment by eusonlito** [comment]
You can extend package `Meta` class and add the `config('app.url')` for each image (remember, you should never use `env` helper into your source code, only on config files).

```php
# app/Services/Html/Meta.php

<?php
namespace App\Services\Html;

class Meta extends \Meta
{
    /**
     * @param  string $value
     *
     * @return string
     */
    protected function setImage($value)
    {
        if (count($this->metas['image']) >= $this->config['image_limit']) {
            return '';
        }

        $this->metas['image'][] = config('app.url').$value;

        return $value;
    }
}
```

```php
# config/app.php

'aliases' => [
   ...

   'Meta' => App\Services\Html\Meta::class,

   ...
];
```

**Comment by bellwood** [comment]
Thank you very much...
