### ISSUE TITLE
Preventing unwanted duplicate tags

### ISSUE THREAD

**Issue by bellwood** [eusonlito/laravel-Meta#28]
When trying to add twitter cards:

```
{!! Meta::tag('card') !!}
```

I am seeing the following rendered:

```
<meta name="card" content="Summary" />
<meta name="twitter:card" content="Summary" />
```

...when all I want is:

```
<meta name="twitter:card" content="Summary" />
```

I see some granularity was added in 2.0 but I don't see a way to call `Meta::tagTwitterCard` or similar.

Thank you.

**Comment by chuckreynolds** [comment]
@bellwood just add 
1. `Meta::set('twitter:card', 'summary');` to your controller 
1. `{!! Meta::tag('twitter:card') !!}` to your blade template to display it 

_edit_
OR just add `{!! Meta::tag('twitter:card', 'summary') !!}` to your main blade to set the default
