### ISSUE TITLE
How to prevent a second title tag from being rendered

### ISSUE THREAD

**Issue by anchetaWern** [eusonlito/laravel-Meta#31]
Hello! Thank you for this library. I just have a bit of issue. I'm already handling the `<title>` tag myself so it would be great if this library didn't set it separately if I use: 

```
Meta::title('Some title');
```

All I want is the meta title tag:

```
<meta name="title" content="Some title" />
<meta property="og:title" content="Some title" />
<meta name="twitter:title" content="Some title" />
```

Currently it's also rendering the title tag:

```
<title>Some title</title>
```

**Comment by eusonlito** [comment]
Tags are printed together, you should print all `title` tags with your own html code.
