### ISSUE TITLE
[Suggestion] Make facade detectable by Laravel Idea plugin for PhpStorm

### ISSUE THREAD

**Issue by keevitaja** [eusonlito/laravel-Meta#34]
Hello!

Currently this package does not let detect facade target with Laravel Idea Plugin, because it just returns an arbitrary string instead of FQCN.

Would you consider following?

```php
use Illuminate\Support\Facades\Facade;

class Meta extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return \Eusonlito\LaravelMeta\Meta::class;
    }
}
```

```php
        $this->app->singleton(Eusonlito\LaravelMeta\Meta::class, function () {
            return new Meta(config('meta'));
        });
```

end result is the same, cause this string is really not used for anything else than binding!

**Comment by eusonlito** [comment]
Done! Release https://github.com/eusonlito/laravel-Meta/releases/tag/v3.3.0
