### ISSUE TITLE
Setters in app\Http\Controllers\Controller::__construct are not working

### ISSUE THREAD

**Issue by jartaud** [eusonlito/laravel-Meta#5]
When not setting in the current Controller,  it falls back to the config ignoring app\Http\Controllers\Controller::__construct .

**Comment by eusonlito** [comment]
Please, paste your code here :)

**Comment by jartaud** [comment]
Sorry. I was not calling parent::__construct() in my HomeController. By the way I'm using a fork from your package with L5.2.
