### ISSUE TITLE
Incompatible with ide-helper

### ISSUE THREAD

**Issue by f-liva** [eusonlito/laravel-Meta#7]
The type hinting used in the Meta::__construct gets the package incompatible with barryvdh/laravel-ide-helper, which passes a null value to the constructor and throw an error.

> php artisan ide-helper:generate

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to Eusonlito\LaravelMeta\Meta::__construct()
  must be of the type array, null given, called in D:\Progetti\studioelps.com
  \StudioElps\vendor\eusonlito\laravel-meta\src\Eusonlito\LaravelMeta\MetaSer
  viceProvider.php on line 35

**Comment by eusonlito** [comment]
Ok, I will check it ASAP :+1:

**Comment by f-liva** [comment]
Removing the array type hint in the first parameter of the constructor
solves the problem.

Il mer 27 apr 2016, 00:42 Lito notifications@github.com ha scritto:
