### ISSUE TITLE
Bug with characters

### ISSUE THREAD

**Issue by MaMouT514** [eusonlito/laravel-Meta#9]
Hi,
Something strange with some utf-8 characters (I'm french) :
In fact, with "é" no problem but with "à", I've got "�"...
Any idea ?
Thanks!

**Comment by eusonlito** [comment]
Yes, it's strange because I'm using spanish as language without any character problem.

I have testes now "à" as title meta without problem.

Can you paste a full code example?

**Comment by MaMouT514** [comment]
In my controller :

``` php
use Meta;
class FrontendController extends Controller
{
    public function home()
    {
       Meta::set('title', 'Venez découvrir nos événements à Paris');
        return view('frontend.pages.home');
    }
}
```

In my view :

``` html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="fr" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="fr" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="fr"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="_token" content="{{ csrf_token() }}" />
    <?= Meta::tag('title'); ?>
    <?= Meta::tag('robots'); ?>
    <?= Meta::tag('url', Request::url()); ?>
    <?= Meta::tag('locale', 'fr_FR'); ?>
    <?= Meta::tag('description'); ?>
    <?= Meta::tag('image'); ?>...
```

And the result : 

``` html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="fr" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="fr" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="fr"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="_token" content="CZE5IyU4Q6VcrRPw499MWnyzrCCzjgm2U9Xp2rCN" />
    <title>Venez découvrir nos événements � Paris</title><meta name="title" content="Venez découvrir nos événements � Paris" /><meta property="og:title" content="Venez découvrir nos événements � Paris" /><meta name="twitter:title" content="Venez découvrir nos événements � Paris" /> ...`
```

My website is based on Laravel 5 Boilerplate (https://github.com/rappasoft/laravel-5-boilerplate), composer update done and cache clear!

**Comment by eusonlito** [comment]
This string is a copy/paste from another document?

Can you test to write yourself the phrase?

I have checked these code in an empty project without problem.

**Comment by MaMouT514** [comment]
I've just checked too in an empty project... and same problem.
Maybe windows ?

**Comment by eusonlito** [comment]
It's possible, now I have tested this code into a clean laravel-5-boilerplate installation without problem.

Maybe some charset conflict in windows... if `é` is printed fine, `à` must be also.

**Comment by MaMouT514** [comment]
`è` is printed fine...
I think that is a problem on my dev computer.
Thanks for your help and your module!

**Comment by sergeyklay** [comment]
Mb UTF-8 with **BOM**?

**Comment by MaMouT514** [comment]
@sergeyklay Can you explain ? I don't get it..
Thanks

**Comment by eusonlito** [comment]
Here some additional info http://stackoverflow.com/questions/2554445/how-to-fix-byte-order-mark-found-in-utf-8-file-validation-warning

You can test it also with sublime text (File > Save with encoding > UTF-8).

**Comment by MaMouT514** [comment]
Ok, I've got it but it was one of the first thing I've checked... 
I've check again and no change

**Comment by MaMouT514** [comment]
No problem in production...
So I've got a problem with my computer. 
Sorry!
